require(igraph)
graphics.off()
data_y2h = as.matrix(read.table('tc01_data/yeast_Y2H.txt'))
g_y2h = graph_from_edgelist(data_y2h)
pdf('pdf1.pdf')
plot(g_y2h,vertex.label=NA,vertex.size=1,edge.arrow.size=0.3,edge.color='black')
#x11()
plot(simplify(g_y2h),vertex.label=NA,vertex.size=1,edge.arrow.size=0.3,edge.color='black')
clst_y2h = clusters(g_y2h)
CG_y2h = induced_subgraph(g_y2h,clst_y2h$membership==which.max(clst_y2h$csize))
plot(simplify(CG_y2h),vertex.label=NA,vertex.size=1,edge.arrow.size=0.3,edge.color='black')
sueltas_y2h = induced_subgraph(g_y2h,clst_y2h$membership!=which.max(clst_y2h$csize))
plot(simplify(sueltas_y2h),vertex.label=NA,vertex.size=1,edge.arrow.size=0.3,edge.color='black')
dev.off()
