require(igraph)
require(Matrix)
graphics.off()
pdf('ej4.pdf')
g = read_graph('tc01_data/as-22july06.gml',format='gml')
h = read_graph('tc01_data/netscience.gml',format='gml')
Ag=as_adjacency_matrix(g)
Ah=as_adjacency_matrix(h)
knng=as.numeric(Ag%*%Ag%*%rep(1,length(V(g))))/as.numeric(degree(g))
knngAgg=aggregate(knng,list('k'=degree(g)),mean)
knnh=as.numeric(Ah%*%Ah%*%rep(1,length(V(h))))/as.numeric(degree(h))
knnhAgg=aggregate(knnh,list('k'=degree(h)),mean)
xg=log(knngAgg$k[knngAgg$k>0 & knngAgg$x>0])
yg=log(knngAgg$x[knngAgg$k>0 & knngAgg$x>0])
modg=lm(yg~xg)
xh=log(knnhAgg$k[knnhAgg$k>0 & knnhAgg$x>0])
yh=log(knnhAgg$x[knnhAgg$k>0 & knnhAgg$x>0])
modh=lm(yh~xh)

plot(knngAgg$k,knngAgg$x,xlab='grado',ylab='media de grados de vecinos')
lines(exp(xg),exp(predict(modg)),col='blue')
plot(knngAgg$k,knngAgg$x,xlab='grado',ylab='media de grados de vecinos',log='xy')
lines(exp(xg),exp(predict(modg)),col='blue')
plot(knnhAgg$k,knnhAgg$x,xlab='grado',ylab='media de grados de vecinos',pch=0)
lines(exp(xh),exp(predict(modh)),col='blue')
plot(knnhAgg$k,knnhAgg$x,xlab='grado',ylab='media de grados de vecinos',log='xy',pch=0)
lines(exp(xh),exp(predict(modh)),col='blue')
dev.off()
